### ISSUE TITLE
"Enter your text" is above the text box in text element

### ISSUE THREAD

**Issue by MathuraMG** [peblio/proto-2#97]

**Comment by MathuraMG** [comment]
This was fixed with #95

**Comment by estherhersh** [comment]
<img width="374" alt="screen shot 2018-01-15 at 5 00 08 pm" src="https://user-images.githubusercontent.com/14132409/34970572-f1e9ebe4-fa29-11e7-9bb1-59abb901f5f1.png">
this is still happening for me
